In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [9]:
block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words:
  
  # print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context) # current running context ...,..e,.em, emm, mma,ma.
    Y.append(ix) #current char
    # print(context)
    # print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # remove first item and add target char
  
X = torch.tensor(X) #each row contains 3 char context
Y = torch.tensor(Y)

In [6]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([228146, 3]), torch.int64, torch.Size([228146]), torch.int64)

In [10]:
C = torch.randn((27,2)) #rand nums two col

In [11]:
C[5]

tensor([ 0.5788, -1.4944])

In [15]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C #trigger 5th index as high

tensor([ 0.5788, -1.4944])

In [17]:
X[13,2]

tensor(1)

In [16]:
C[X][13,2] #multi dimensional, Replace every index in X with corresponding row from C
#take example #13
#take 3rd character in context (index 2)

#Returns that character’s embedding vector.

tensor([-1.3827,  1.0722])

In [18]:
C[1]

tensor([-1.3827,  1.0722])

In [19]:
emb = C[X]
emb.shape

torch.Size([228146, 3, 2])

In [21]:
w1 = torch.randn((6,100))
b1 = torch.randn(100)

In [22]:
emb @ W1 + b1

NameError: name 'W1' is not defined